In [1]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


### Importing the Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Importing the Dataset

In [3]:
data = pd.read_csv('/content/gdrive/My Drive/RS/symptoms_diseases.csv')

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
data.head()

Disease  itching   skin_rash   continuous_sneezing   shivering  \
0  Fungal infection        1           1                     0           0   
1  Fungal infection        0           1                     0           0   
2  Fungal infection        1           0                     0           0   
3  Fungal infection        1           1                     0           0   
4  Fungal infection        1           1                     0           0   

    stomach_pain   acidity   vomiting   indigestion   muscle_wasting  \
0              0         0          0             0                0   
1              0         0          0             0                0   
2              0         0          0             0                0   
3              0         0          0             0                0   
4              0         0          0             0                0   

    patches_in_throat   fatigue   weight_loss   sunken_eyes   cough  \
0                   0         0             0             0       0   
1                   0         0             0             0       0   
2                   0         0             0             0       0   
3                   0         0             0             0       0   
4                   0         0             0             0       0   

    headache   chest_pain   back_pain   weakness_in_limbs   chills  \
0          0            0           0                   0        0   
1          0            0           0                   0        0   
2          0            0           0                   0        0   
3          0            0           0                   0        0   
4          0            0           0                   0        0   

    joint_pain   yellowish_skin   constipation   pain_during_bowel_movements  \
0            0                0              0                             0   
1            0                0              0                             0   
2            0                0              0                             0   
3            0                0              0                             0   
4            0                0              0                             0   

    breathlessness   cramps   weight_gain   mood_swings   neck_pain  \
0                0        0             0             0           0   
1                0        0             0             0           0   
2                0        0             0             0           0   
3                0        0             0             0           0   
4                0        0             0             0           0   

    muscle_weakness   stiff_neck   pus_filled_pimples   burning_micturition  \
0                 0            0                    0                     0   
1                 0            0                    0                     0   
2                 0            0                    0                     0   
3                 0            0                    0                     0   
4                 0            0                    0                     0   

    bladder_discomfort   high_fever   nodal_skin_eruptions   ulcers_on_tongue  \
0                    0            0                      1                  0   
1                    0            0                      1                  0   
2                    0            0                      1                  0   
3                    0            0                      0                  0   
4                    0            0                      1                  0   

    loss_of_appetite   restlessness   dehydration   dizziness  \
0                  0              0             0           0   
1                  0              0             0           0   
2                  0              0             0           0   
3                  0              0             0           0   
4                  0              0             0           0   

 

In [6]:
data = data.drop(columns=['Unnamed: 74'], axis = 1)

In [7]:
data.head()

Disease  itching   skin_rash   continuous_sneezing   shivering  \
0  Fungal infection        1           1                     0           0   
1  Fungal infection        0           1                     0           0   
2  Fungal infection        1           0                     0           0   
3  Fungal infection        1           1                     0           0   
4  Fungal infection        1           1                     0           0   

    stomach_pain   acidity   vomiting   indigestion   muscle_wasting  \
0              0         0          0             0                0   
1              0         0          0             0                0   
2              0         0          0             0                0   
3              0         0          0             0                0   
4              0         0          0             0                0   

    patches_in_throat   fatigue   weight_loss   sunken_eyes   cough  \
0                   0         0             0             0       0   
1                   0         0             0             0       0   
2                   0         0             0             0       0   
3                   0         0             0             0       0   
4                   0         0             0             0       0   

    headache   chest_pain   back_pain   weakness_in_limbs   chills  \
0          0            0           0                   0        0   
1          0            0           0                   0        0   
2          0            0           0                   0        0   
3          0            0           0                   0        0   
4          0            0           0                   0        0   

    joint_pain   yellowish_skin   constipation   pain_during_bowel_movements  \
0            0                0              0                             0   
1            0                0              0                             0   
2            0                0              0                             0   
3            0                0              0                             0   
4            0                0              0                             0   

    breathlessness   cramps   weight_gain   mood_swings   neck_pain  \
0                0        0             0             0           0   
1                0        0             0             0           0   
2                0        0             0             0           0   
3                0        0             0             0           0   
4                0        0             0             0           0   

    muscle_weakness   stiff_neck   pus_filled_pimples   burning_micturition  \
0                 0            0                    0                     0   
1                 0            0                    0                     0   
2                 0            0                    0                     0   
3                 0            0                    0                     0   
4                 0            0                    0                     0   

    bladder_discomfort   high_fever   nodal_skin_eruptions   ulcers_on_tongue  \
0                    0            0                      1                  0   
1                    0            0                      1                  0   
2                    0            0                      1                  0   
3                    0            0                      0                  0   
4                    0            0                      1                  0   

    loss_of_appetite   restlessness   dehydration   dizziness  \
0                  0              0             0           0   
1                  0              0             0           0   
2                  0              0             0           0   
3                  0              0             0           0   
4                  0              0             0           0   

 

In [8]:
X = data.drop(["Disease"],axis = 1)
y = data['Disease']

In [9]:
X.shape

(4920, 131)

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4920 entries, 0 to 4919
Columns: 132 entries, Disease to  loss_of_smell
dtypes: int64(131), object(1)
memory usage: 5.0+ MB


In [11]:
# Splitting into training and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state =0, test_size= 0.20)

In [12]:
print('Training Set: ', len(X_train))
print('Test Set: ', len(X_test))
print('Training Labels: ', len(y_train))
print('Test Labels: ', len(y_test))

Training Set:  3936
Test Set:  984
Training Labels:  3936
Test Labels:  984


### Naive Bayes Classifier

In [13]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import KFold, cross_val_score, GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [14]:
nb = GaussianNB()
nb.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [15]:
y_pred = nb.predict(X_test)

In [16]:
# Confusion Matrix
y_pred = nb.predict(X_test)
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred)) 

[[18  0  0 ...  0  0  0]
 [ 0 22  0 ...  0  0  0]
 [ 0  0 31 ...  0  0  0]
 ...
 [ 0  0  0 ... 20  0  0]
 [ 0  0  0 ...  0 28  0]
 [ 0  0  0 ...  0  0 24]]
                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        18
                                   AIDS       1.00      1.00      1.00        22
                                   Acne       1.00      1.00      1.00        31
                    Alcoholic hepatitis       1.00      1.00      1.00        24
                                Allergy       1.00      1.00      1.00        23
                              Arthritis       1.00      1.00      1.00        23
                       Bronchial Asthma       1.00      1.00      1.00        28
                   Cervical spondylosis       1.00      1.00      1.00        27
                            Chicken pox       1.00      1.00      1.00        21
                    Chronic chole

In [17]:
print('Accuracy Score: '+ str(accuracy_score(y_test, y_pred)*100)+ ' %')

Accuracy Score: 100.0 %


### Prediction

In [18]:
symptoms_categoty = {}

for index, symptom in enumerate(X):
    symptoms_categoty[symptom] = index

In [19]:
symptoms_categoty

{' abdominal_pain': 43,
 ' abnormal_menstruation': 121,
 ' acidity': 5,
 ' acute_liver_failure': 118,
 ' altered_sensorium': 61,
 ' anxiety': 48,
 ' back_pain': 16,
 ' belly_pain': 116,
 ' blackheads': 51,
 ' bladder_discomfort': 32,
 ' blister': 54,
 ' blood_in_sputum': 129,
 ' bloody_stool': 64,
 ' blurred_and_distorted_vision': 60,
 ' breathlessness': 23,
 ' brittle_nails': 107,
 ' bruising': 46,
 ' burning_micturition': 31,
 ' chest_pain': 15,
 ' chills': 18,
 ' cold_hands_and_feets': 47,
 ' coma': 123,
 ' congestion': 128,
 ' constipation': 21,
 ' continuous_feel_of_urine': 70,
 ' continuous_sneezing': 2,
 ' cough': 13,
 ' cramps': 24,
 ' dark_urine': 62,
 ' dehydration': 38,
 ' depression': 92,
 ' diarrhoea': 58,
 ' dischromic _patches': 55,
 ' distention_of_abdomen': 80,
 ' dizziness': 39,
 ' drying_and_tingling_lips': 108,
 ' enlarged_thyroid': 104,
 ' excessive_hunger': 78,
 ' extra_marital_contacts': 57,
 ' family_history': 76,
 ' fast_heart_rate': 98,
 ' fatigue': 10,
 ' flu

In [20]:
input_vector = np.zeros(len(symptoms_categoty))

In [21]:
input_vector[[symptoms_categoty[' watering_from_eyes'], symptoms_categoty[' anxiety']]] = 1

In [22]:
nb.predict([input_vector])[0]

'Allergy'

### Saving the Model

In [23]:
from joblib import dump, load
dump(nb, '/content/gdrive/My Drive/RS/nb.joblib') 

['/content/gdrive/My Drive/RS/nb.joblib']

In [24]:
model = load('/content/gdrive/My Drive/RS/nb.joblib')

In [25]:
model.predict([input_vector])[0]

'Allergy'